[tweaks]
autoClimbLadder = false
doNotUseLastTorch = false
hideOffhandItem = false
hideOwnParticleEffects = false
hideShieldUnlessHoldingWeapon = true
noOffhandTorchAtAll = false
noOffhandTorchWithBlock = true
noOffhandTorchWithEmptyHand = false
offhandTorchWithToolOnly = false
disableStepAssist = false
masterVolumeSlider = true
musicVolumeSlider = true
[customization]
torchItems = ["minecraft:torch", "minecraft:soul_torch", "tconstruct:stone_torch"]
torchTools = ["minecraft:wooden_pickaxe", "minecraft:stone_pickaxe", "minecraft:iron_pickaxe", "minecraft:golden_pickaxe", "minecraft:diamond_pickaxe", "minecraft:netherite_pickaxe", "tconstruct:pickaxe", "tconstruct:hammer"]
offhandTorchTools = ["tconstruct:shovel", "tconstruct:excavator"]
shieldWeapons = ["tetra:modular_sword"]
