module = "NO_NAME"

[noName]
margin = 10
squash = false
effectsPerColumn = 4
leftSide = true
showLevel = true
levelInArabic = false

[noSprite]
margin = 10
squash = false
effectsPerColumn = 5
leftSide = true

[onlyName]
margin = 10
effectsPerColumn = 8
leftSide = true
squash = false
permanentColour = 16777215
wontExpireSoonColour = 45065
soonToExpireColour = 13946112
expiringColour = 13893632
expiringBound = 20
soonToExpireBound = 60
