#Couple regardless of whether the player is sneaking when interacting
ignore_sneaking = true
#Couple neighboring fence gates above and below on the same axis
couple_fence_gates = true
#Couple neighboring doors with opposing hinges
couple_doors = true
#Couple neighboring trapdoors along either sides and opposing
couple_trapdoors = false

