MAX_ENCHANTMENT_TEXT = true
EASTER_EGGS = false

[ALL_GOBLIN_TRADERS_CONFIG]
FIND_COOLDOWN = 2400
FALL = true
NO_ATTACK_CREATIVE = true
CAN_GET_KNOCKED_OUT = false

[GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = true
SPAWN_CHANCE = 25
SPAWN_DELAY = 24000
MAX_SPAWN_HEIGHT = 63
MIN_SPAWN_HEIGHT = -64

[VEIN_GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = true
SPAWN_CHANCE = 25
SPAWN_DELAY = 24000
MAX_SPAWN_HEIGHT = 127
MIN_SPAWN_HEIGHT = 0
DAMAGED_IN_WATER = false
