[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
priority = "GRAVE"
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
applyBindingCurse = true
trySoft = true
tryStrict = true
blacklistDimensions = []
graveInVoid = true
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
putXpInGrave = true
defaultXpDrop = false
xpDropPercent = 50
tellDeathPos = true

[graveSettings.graveRobbing]
enableRobbing = false
onlyMurderer = false
afterTime = 0
timeType = "MINUTES"
robPriority = "INVENTORY"

[graveSettings.graveDeletion]
canDelete = false
afterTime = 1
timeType = "HOURS"
dropInventory = false

[graveSettings.itemLoss]
enableLoss = false
ignoreSoulboundItems = true
affectStacks = false
usePercentRange = false
lossRangeFrom = 0
lossRangeTo = 5
percentChanceOfLoss = 100

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveRenderSettings]
useRenderFeatures = true
renderGraveSkull = true
renderGraveOwner = true
textShadow = true
adaptRenderer = false
glowingGrave = false
glowMinDistance = 10
glowMaxDistance = 10
[utilitySettings]
soulboundEnchant = true
deathSightEnchant = false

[utilitySettings.scrollItem]
scrollType = "DISABLED"
retrieveOnRespawn = true
[commandToggles]
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
